#cloud-config
package_update: true
package_upgrade: true

# if you're already installing other packages, you may
# wish to manually install ansible to avoid multiple calls
# to your package manager
packages:
  - httpd
runcmd:
  - systemctl start httpd
  - sudo systemctl enable httpd